services:
    # client:
    #   build:
    #   context: ./client
    #   dockerfile: Dockerfile
    #   env_file:
    #     - ./client/.env
    #   ports:
    #     - "3000:3000"
    #   depends_on:
    #     - server

    # server:
    #   server:
    #   build:
    #     context: ./server
    #     dockerfile: Dockerfile
    #   env_file:
    #     - ./server/.env
    #   ports:
    #     - "5000:5000"
