export const adrFormCategoricalValues = {
	patientGender: [
		{ value: "male", label: "Male" },
		{ value: "female", label: "Female" },
	],
	pregnancyStatus: [
		{ value: "not applicable", label: "Not Applicable" },
		{ value: "not pregnant", label: "Not Pregnant" },
		{ value: "1st trimester", label: "1st Trimester" },
		{ value: "2nd trimester", label: "2nd Trimester" },
		{ value: "3rd trimester", label: "3rd Trimester" },
	],
	knownAllergy: [
		{ value: "yes", label: "Yes" },
		{ value: "no", label: "No" },
	],
	route: [
		{ value: "oral", label: "Oral" },
		{ value: "IV", label: "IV" },
	],
	rechallenge: [
		{ value: "yes", label: "Yes" },
		{ value: "no", label: "No" },
		{ value: "unknown", label: "Unknown" },
		{ value: "na", label: "NA" },
	],
	dechallenge: [
		{ value: "yes", label: "Yes" },
		{ value: "no", label: "No" },
		{ value: "unknown", label: "Unknown" },
		{ value: "na", label: "NA" },
	],
	severity: [
		{ value: "mild", label: "Mild" },
		{ value: "moderate", label: "Moderate" },
		{ value: "severe", label: "Severe" },
		{ value: "fatal", label: "Fatal" },
		{ value: "unknown", label: "Unknown" },
	],
	isSerious: [
		{ value: "yes", label: "Yes" },
		{ value: "no", label: "No" },
	],
	criteriaForSeriousness: [
		{ value: "hospitalisation", label: "Hospitalisation" },
		{ value: "disability", label: "Disability" },
		{ value: "congenital anomaly", label: "Congenital Anomaly" },
		{ value: "life-threatening", label: "Life-threatening" },
		{ value: "death", label: "Death" },
	],
	actionTaken: [
		{ value: "drug withdrawn", label: "Drug Withdrawn" },
		{ value: "dose reduced", label: "Dose Reduced" },
		{ value: "dose increased", label: "Dose Increased" },
		{ value: "dose not changed", label: "Dose Not Changed" },
		{ value: "not applicable", label: "Not Applicable" },
		{ value: "unknown", label: "Unknown" },
	],
	outcome: [
		{ value: "recovered", label: "Recovered" },
		{ value: "recovered with sequelae", label: "Recovered with Sequelae" },
		{ value: "recovering", label: "Recovering" },
		{ value: "not recovered", label: "Not Recovered" },
		{ value: "death", label: "Death" },
		{ value: "unknown", label: "Unknown" },
	],
};

const counties = [
	{ value: "Baringo", label: "Baringo" },
	{ value: "Bomet", label: "Bomet" },
	{ value: "Bungoma", label: "Bungoma" },
	{ value: "Busia", label: "Busia" },
	{ value: "Elgeyo Marakwet", label: "Elgeyo Marakwet" },
	{ value: "Embu", label: "Embu" },
	{ value: "Garissa", label: "Garissa" },
	{ value: "Homa Bay", label: "Homa Bay" },
	{ value: "Isiolo", label: "Isiolo" },
	{ value: "Kajiado", label: "Kajiado" },
	{ value: "Kakamega", label: "Kakamega" },
	{ value: "Kericho", label: "Kericho" },
	{ value: "Kiambu", label: "Kiambu" },
	{ value: "Kilifi", label: "Kilifi" },
	{ value: "Kirinyaga", label: "Kirinyaga" },
	{ value: "Kisii", label: "Kisii" },
	{ value: "Kisumu", label: "Kisumu" },
	{ value: "Kitui", label: "Kitui" },
	{ value: "Kwale", label: "Kwale" },
	{ value: "Laikipia", label: "Laikipia" },
	{ value: "Lamu", label: "Lamu" },
	{ value: "Machakos", label: "Machakos" },
	{ value: "Makueni", label: "Makueni" },
	{ value: "Mandera", label: "Mandera" },
	{ value: "Marsabit", label: "Marsabit" },
	{ value: "Meru", label: "Meru" },
	{ value: "Migori", label: "Migori" },
	{ value: "Mombasa", label: "Mombasa" },
	{ value: "Murang'a", label: "Murang'a" },
	{ value: "Nairobi", label: "Nairobi" },
	{ value: "Nakuru", label: "Nakuru" },
	{ value: "Nandi", label: "Nandi" },
	{ value: "Narok", label: "Narok" },
	{ value: "Nyamira", label: "Nyamira" },
	{ value: "Nyandarua", label: "Nyandarua" },
	{ value: "Nyeri", label: "Nyeri" },
	{ value: "Samburu", label: "Samburu" },
	{ value: "Siaya", label: "Siaya" },
	{ value: "Taita Taveta", label: "Taita Taveta" },
	{ value: "Tana River", label: "Tana River" },
	{ value: "Tharaka Nithi", label: "Tharaka Nithi" },
	{ value: "Trans Nzoia", label: "Trans Nzoia" },
	{ value: "Turkana", label: "Turkana" },
	{ value: "Uasin Gishu", label: "Uasin Gishu" },
	{ value: "Vihiga", label: "Vihiga" },
	{ value: "Wajir", label: "Wajir" },
	{ value: "West Pokot", label: "West Pokot" },
];
